export const enum RoutersPath {
  home = '/',
  profile = '/profile',
  signIn = '/sign-in',
  signUp = '/sign-up',
  sentEmail = '/sent-email',
  mergeAccounts = '/merge-accounts',
  forgotPassword = '/forgot-password',
  createNewPassword = '/create-new-password',
  invalidVerificationLink = '/invalid-verification-link',
  authExpiredVerificationLink = '/auth/expired-verification-link',
  authRegistrationConfirmation = '/auth/registration-confirmation',
  authTermsOfService = '/auth/terms-of-service',
  authPrivacyPolicy = '/auth/privacy-policy',
  authConfirmedEmail = '/auth/confirmed-email',
  profileGeneralInformation = '/profile/general-information',
  profileDevices = '/profile/devices',
  profileAccountManagement = '/profile/account-management',
  profileMyPayments = '/profile/my-payments',
  folderNextStaticMedia = '/_next/static/media/',
  superAdminUsersList = '/super-admin/users-list',
  superAdminStatistics = '/super-admin/statistics',
  superAdminPaymentsList = '/super-admin/payments-list',
  superAdminPostsList = '/super-admin/posts-list',
  apiAuthGithubLogin = 'https://inctagram.work/api/v1/auth/github/login',
  apiAuthGoogleLogin = 'https://inctagram.work/api/v1/auth/google/login',
}
