export const enum RoutersPath {
  profile = '/profile',
  signIn = '/sign-in',
  signUp = '/sign-up',
  sentEmail = '/sent-email',
  mergeAccounts = '/merge-accounts',
  forgotPassword = '/forgot-password',
  createNewPassword = '/create-new-password',
  invalidVerificationLink = '/invalid-verification-link',
  authExpirredVerificationLink = '/auth/expired-verification-link',
  authRegistrationConfirmation = '/auth/registration-confirmation',
  authTermsOfService = '/auth/terms-of-service',
  authPrivacyPolicy = '/auth/privacy-policy',
  authConfirmedEmail = '/auth/confirmed-email',
  profileGeneralInformation = '/profile/general-information',
  profileDevices = '/profile/devices',
  profileAccountManagement = '/profile/account-management',
  profileMyPayments = '/profile/my-payments',
  folderNextStaticMedia = '/_next/static/media/',
  apiAuthGithubLogin = 'https://inctagram.work/api/v1/auth/github/login',
}
