export { CreateNewPassForm } from './ui/CreateNewPassForm/CreateNewPassForm'
export { Sign } from './ui/SignInForm/Sign'
export { SignInForm } from './ui/SignInForm/SignInForm'
export { SignUpForm } from './ui/SignUpForm/SignUpForm'
export { ForgotPass } from './ui/ForgotPassForm/ForgotPassForm'
